# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2015-2018, Intel Corporation

LIBRARIES = hashmap_atomic hashmap_tx hashmap_tx_unsafe hashmap_rp 

LIBS = -lpmemobj

include ../../Makefile.inc

libhashmap_atomic.o: hashmap_atomic.o
libhashmap_tx.o: hashmap_tx.o
libhashmap_tx_unsafe.o: hashmap_tx_unsafe.o
libhashmap_rp.o: hashmap_rp.o

